@echo off
echo Setting up Python Virtual Environment for testing...
python -m venv venv
call venv\Scripts\activate
echo Installing requirements...
pip install -r requirements.txt
echo Running pytest...
pytest
pause
